### ISSUE TITLE
What is the difference between this and .xcconfig files?

### ISSUE THREAD

**Issue by silverhawk184** [levibostian/dotenv-ios#19]
Is there a benefit to using .env vs env.xcconfig? They appear to be the same format and the latter is handled natively.

**Comment by levibostian** [comment]
It's been a while since I thought about this question so let me try my best to remember old memories, haha! 

The design decision of this project using `.env` files and to generate Swift source code is for 2 main reasons: 

1. Simplicity. A `.env` file and a Swift source code file is easy to understand with no learning curve. I would argue that `.xcconfig` files *can* have a small learning curve to them compared to just a Swift file with some constants in it. 

Also, `.xcconfig` files have [powerful features](https://nshipster.com/xcconfig/) that a simple environment variable does not need. A Swift file does the job good enough for this use case. 

2. Consistency. I developed this plugin when I was developing nodejs server-side apps, native Android apps, and native iOS apps. I didn't like how each platform used different techniques and tools to use environment variables in the app. I wanted something consistent where each platform used the same design of having a `.env` file and be able to reference those values from code. 

---

Great question! I think this content would be good to add to the readme docs.

**Comment by silverhawk184** [comment]
thank you for the quick response!

**Comment by levibostian** [comment]
Thanks for asking the question 😄
